// Code generated by protoc-gen-go.
// source: mock.proto
// DO NOT EDIT!

/*
Package mock is a generated protocol buffer package.

It is generated from these files:
	mock.proto

It has these top-level messages:
	BaseMsg
	EmptyMsg
*/
package mock

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BaseMsg struct {
	Uint32  uint32 `protobuf:"varint,1,opt,name=Uint32" json:"Uint32,omitempty"`
	Uint64  uint64 `protobuf:"varint,2,opt,name=Uint64" json:"Uint64,omitempty"`
	String_ string `protobuf:"bytes,3,opt,name=String" json:"String,omitempty"`
	Int32   int32  `protobuf:"varint,4,opt,name=Int32" json:"Int32,omitempty"`
	Int64   int64  `protobuf:"varint,5,opt,name=Int64" json:"Int64,omitempty"`
}

func (m *BaseMsg) Reset()                    { *m = BaseMsg{} }
func (m *BaseMsg) String() string            { return proto.CompactTextString(m) }
func (*BaseMsg) ProtoMessage()               {}
func (*BaseMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BaseMsg) GetUint32() uint32 {
	if m != nil {
		return m.Uint32
	}
	return 0
}

func (m *BaseMsg) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

func (m *BaseMsg) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *BaseMsg) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *BaseMsg) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

type EmptyMsg struct {
}

func (m *EmptyMsg) Reset()                    { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string            { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()               {}
func (*EmptyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*BaseMsg)(nil), "mock.BaseMsg")
	proto.RegisterType((*EmptyMsg)(nil), "mock.EmptyMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mock service

type MockClient interface {
	Base(ctx context.Context, in *BaseMsg, opts ...grpc.CallOption) (*EmptyMsg, error)
}

type mockClient struct {
	cc *grpc.ClientConn
}

func NewMockClient(cc *grpc.ClientConn) MockClient {
	return &mockClient{cc}
}

func (c *mockClient) Base(ctx context.Context, in *BaseMsg, opts ...grpc.CallOption) (*EmptyMsg, error) {
	out := new(EmptyMsg)
	err := grpc.Invoke(ctx, "/mock.Mock/Base", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mock service

type MockServer interface {
	Base(context.Context, *BaseMsg) (*EmptyMsg, error)
}

func RegisterMockServer(s *grpc.Server, srv MockServer) {
	s.RegisterService(&_Mock_serviceDesc, srv)
}

func _Mock_Base_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServer).Base(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mock.Mock/Base",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServer).Base(ctx, req.(*BaseMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mock.Mock",
	HandlerType: (*MockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Base",
			Handler:    _Mock_Base_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mock.proto",
}

func init() { proto.RegisterFile("mock.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcd, 0x4f, 0xce,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x6a, 0xb9, 0xd8, 0x9d, 0x12,
	0x8b, 0x53, 0x7d, 0x8b, 0xd3, 0x85, 0xc4, 0xb8, 0xd8, 0x42, 0x33, 0xf3, 0x4a, 0x8c, 0x8d, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0xa0, 0x3c, 0x98, 0xb8, 0x99, 0x89, 0x04, 0x93, 0x02, 0xa3,
	0x06, 0x4b, 0x10, 0x94, 0x07, 0x12, 0x0f, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x97, 0x60, 0x56, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x44, 0xb8, 0x58, 0x3d, 0xc1, 0xc6, 0xb0, 0x28, 0x30, 0x6a,
	0xb0, 0x06, 0x41, 0x38, 0x50, 0x51, 0x33, 0x13, 0x09, 0x56, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x08,
	0x47, 0x89, 0x8b, 0x8b, 0xc3, 0x35, 0xb7, 0xa0, 0xa4, 0xd2, 0xb7, 0x38, 0xdd, 0x48, 0x9f, 0x8b,
	0xc5, 0x37, 0x3f, 0x39, 0x5b, 0x48, 0x9d, 0x8b, 0x05, 0xe4, 0x24, 0x21, 0x5e, 0x3d, 0xb0, 0x6b,
	0xa1, 0xce, 0x93, 0xe2, 0x83, 0x70, 0x61, 0xca, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x1e, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x09, 0x7c, 0x02, 0xd6, 0x00, 0x00, 0x00,
}
